import type { Config } from "tailwindcss";

/** Sentinel Command / Stitch design tokens (from stitch HTML exports) */
const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#111316",
        surface: "#111316",
        "surface-dim": "#111316",
        "surface-bright": "#37393d",
        "surface-variant": "#333538",
        "surface-tint": "#c1c1ff",
        "surface-container-lowest": "#0c0e11",
        "surface-container-low": "#1a1c1f",
        "surface-container": "#1e2023",
        "surface-container-high": "#282a2d",
        "surface-container-highest": "#333538",
        "on-surface": "#e2e2e6",
        "on-surface-variant": "#c7c4d7",
        "on-background": "#e2e2e6",
        primary: "#c1c1ff",
        "on-primary": "#1200a9",
        "primary-container": "#5d5fef",
        "on-primary-container": "#faf7ff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c1c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2e2bc2",
        secondary: "#ffffff",
        "on-secondary": "#283500",
        "secondary-container": "#c3f400",
        "on-secondary-container": "#556d00",
        "secondary-fixed": "#c3f400",
        "secondary-fixed-dim": "#abd600",
        "on-secondary-fixed": "#161e00",
        "on-secondary-fixed-variant": "#3c4d00",
        tertiary: "#c2c6db",
        "on-tertiary": "#2b3040",
        "tertiary-container": "#6d7184",
        "tertiary-fixed": "#dee1f7",
        "tertiary-fixed-dim": "#c2c6db",
        "on-tertiary-container": "#f8f7ff",
        "on-tertiary-fixed": "#161b2b",
        "on-tertiary-fixed-variant": "#414658",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#908fa0",
        "outline-variant": "#464555",
        "inverse-surface": "#e2e2e6",
        "inverse-on-surface": "#2f3034",
        "inverse-primary": "#4849da",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        body: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        headline: ["var(--font-headline)", "Space Grotesk", "system-ui", "sans-serif"],
        label: ["var(--font-headline)", "Space Grotesk", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        "spin-slow": "spin 4s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
